# @env dev
@Session10_HostAddress = http://localhost:5022/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzQwNDk5MTY1LCJpc3MiOiJNeUFwcCIsImF1ZCI6Ik15VXNlcnMifQ.dfRJgpbO_OpQz5rhII6sXY0O2LP4yi4O9--eKls7c68

### درخواست ورود برای دریافت توکن
POST {{Session10_HostAddress}}/identity/login
Content-Type: application/json

{
  "username": "test1",
  "password": "password"
}

### درخواست دریافت داده محافظت‌شده با ارسال توکن در هدر Authorization
GET {{Session10_HostAddress}}/secured/data
# Authorization: Bearer {{token}}

###
GET {{Session10_HostAddress}}/secured/data2